heat solver: Fixed index going out of bounds
When attempting solving impossible heat goals and ranges, algo runs out of prebaked DX1 values.
1. Fixed incorrect loop condition that caused the out of bounds.
2. Clamped the heat goal so they also never attempt to solve impossible heat goals.

Stacktrace
----------
java.lang.ArrayIndexOutOfBoundsException: Index 27 out of bounds for length 27
    at com.toofifty.easygiantsfoundry.HeatActionSolver.relativeSolve(HeatActionSolver.java:188)
    at com.toofifty.easygiantsfoundry.HeatActionSolver.heatingSolve(HeatActionSolver.java:136)
    at com.toofifty.easygiantsfoundry.HeatActionSolver.solve(HeatActionSolver.java:288)
    at com.toofifty.easygiantsfoundry.FoundryOverlay3D.drawHeatChangerPreviewOverlay(FoundryOverlay3D.java:244)